export default {
  home: {
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '2.5rem', // 40px
    letterSpacing: '0em',
    textAlign: 'center',
  },
  homeMobile: {
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontWeight: 500,
    lineHeight: '24px', // 40px
    letterSpacing: '0em',
  },
  navbar: {
    fontFamily: 'Poppins',
    fontSize: '24px',
    fontWeight: 500,
    lineHeight: '36px',
    letterSpacing: '0em',
    textAlign: 'left',
    color: '#FFFFFF',
  },
  servicesCardTitle: {
    fontFamily: 'Send Flowers',
    fontSize: '45px',
    fontWeight: 400,
    lineHeight: '59.63px',
    letterSpacing: '0em',
    textAlign: 'center',
    color: '#B09D59',
  },
  servicesCardDesc: {
    fontFamily: 'Poppins',
    fontSize: '18px',
    fontWeight: 400,
    lineHeight: '27px',
    letterSpacing: '0em',
    textAlign: 'center',
    color: '#FFFFFF',
  },
  sectionTitle: {
    fontFamily: 'Send Flowers',
    fontSize: '60px',
    fontWeight: 400,
    lineHeight: '79.5px',
    letterSpacing: '0em',
    textAlign: 'center',
    color: '#B09D59',
  },
  descCaption: {
    fontFamily: 'Poppins',
    fontSize: '18px',
    fontWeight: 400,
    lineHeight: '27px',
    letterSpacing: '0em',
    textAlign: 'left',
    color: '#000',
  },
}
